config/routes.rb
Rails.application.routes.draw do
  resources :items do
  	collection { post :import}
  end
  resources :areas do
  	collection { post :import}
  end
  resources :catalogs do
  	collection { post :import}
  end
  root to: 'items#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
require 'csv'
class Area < ApplicationRecord
  belongs_to :catalog
  has_many :items, dependent: :destroy

    def self.import(file)
    	CSV.foreach(file.path, headers: true) do |row|
        area = Area.new(name: row["name"])
        area.catalog_id = Catalog.where(name: row["Catalog"]).to_a.first.id
        area.save
  		end
    end
end

app/models/catalog.rb
require 'csv'
class Catalog < ApplicationRecord
	has_many :areas, dependent: :destroy

  def self.import(file)
  	CSV.foreach(file.path, headers: true) do |row|
  		Catalog.create! row.to_hash
  	
	end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :area

    def self.import(file)
    	CSV.foreach(file.path, headers: true) do |row|
        item = Item.new(name: row["name"])
        item.area_id = Area.where(name: row["Area"]).to_a.first.id
        item.save
  		end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :set_area, only: [:show, :edit, :update, :destroy]

  # GET /areas
  # GET /areas.json
  def index
    @areas = Area.all
  end

  # GET /areas/1
  # GET /areas/1.json
  def show
  end

  # GET /areas/new
  def new
    @area = Area.new
  end

  # GET /areas/1/edit
  def edit
  end

  # POST /areas
  # POST /areas.json
  def create
    @area = Area.new
    @area.name = area_params[:name]
    @area.catalog_id = params[:post][:catalog_id]
    respond_to do |format|
      if @area.save
        format.html { redirect_to @area, notice: 'Area was successfully created.' }
        format.json { render :show, status: :created, location: @area }
      else
        puts 'cae en el error de crear area!!!!!!!!!'
        format.html { render :new }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /areas/1
  # PATCH/PUT /areas/1.json
  def update
    respond_to do |format|
      if @area.update(area_params)
        format.html { redirect_to @area, notice: 'Area was successfully updated.' }
        format.json { render :show, status: :ok, location: @area }
      else
        format.html { render :edit }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /areas/1
  # DELETE /areas/1.json
  def destroy
    @area.destroy
    respond_to do |format|
      format.html { redirect_to areas_url, notice: 'Area was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    Area.import(params[:file])
    redirect_to areas_url, notice: 'Áreas importados'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_area
      @area = Area.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def area_params
      params.require(:area).permit(:name, :catalog_id)
    end
end

app/controllers/catalogs_controller.rb
class CatalogsController < ApplicationController
  before_action :set_catalog, only: [:show, :edit, :update, :destroy]

  # GET /catalogs
  # GET /catalogs.json
  def index
    @catalogs = Catalog.all
  end

  # GET /catalogs/1
  # GET /catalogs/1.json
  def show
  end

  # GET /catalogs/new
  def new
    @catalog = Catalog.new
  end

  # GET /catalogs/1/edit
  def edit
  end

  # POST /catalogs
  # POST /catalogs.json
  def create
    @catalog = Catalog.new(catalog_params)

    respond_to do |format|
      if @catalog.save
        format.html { redirect_to @catalog, notice: 'Catalog was successfully created.' }
        format.json { render :show, status: :created, location: @catalog }
      else
        format.html { render :new }
        puts 'cae en ERROR!!!!!'
        format.json { render json: @catalog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /catalogs/1
  # PATCH/PUT /catalogs/1.json
  def update
    respond_to do |format|
      if @catalog.update(catalog_params)
        format.html { redirect_to @catalog, notice: 'Catalog was successfully updated.' }
        format.json { render :show, status: :ok, location: @catalog }
      else
        format.html { render :edit }
        format.json { render json: @catalog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /catalogs/1
  # DELETE /catalogs/1.json
  def destroy
    @catalog.destroy
    respond_to do |format|
      format.html { redirect_to catalogs_url, notice: 'Catalog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    Catalog.import(params[:file])
    redirect_to catalogs_url, notice: 'Items importados'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_catalog
      @catalog = Catalog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def catalog_params
      params.require(:catalog).permit(:name)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new
    @item.name = item_params[:name]
    @item.area_id = params[:post][:area_id]
    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    Item.import(params[:file])
    redirect_to items_url, notice: 'Items importados'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :area_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/catalogs_helper.rb
module CatalogsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/areas/_form.html.erb
<%= form_with(model: area, local: true) do |form| %>
  <% if area.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(area.errors.count, "error") %> prohibited this area from being saved:</h2>

      <ul>
      <% area.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <!-- <div class="field">
    <%= form.label :catalog_id %>
    <%= form.text_field :catalog_id %>
  </div> -->
    
    <%=select("post", "catalog_id", Catalog.all.collect {|p| [ p.name, p.id ] })%>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/areas/edit.html.erb
<h1>Editing Area</h1>

<%= render 'form', area: @area %>

<%= link_to 'Show', @area %> |
<%= link_to 'Back', areas_path %>

app/views/areas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Áreas</h1>

<p>Para subir un área selecciona un archivo .csv </p>
<div style="display: table-caption;">
  <%= form_tag import_areas_path, multipart: true do%>
    <%= file_field_tag :file%>
    <%= submit_tag "Cargar áreas"%>
  <% end %>
</div>


<table>
  <thead>
    <tr>
      <th>Servicio <%= link_to raw("<i class='material-icons left'>add</i>"), new_catalog_path %></th>
      <th>Área <%= link_to raw("<i class='material-icons left'>add</i>"), new_area_path %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @areas.each do |area| %>
      <tr>
        <td><%= area.catalog.name %></td>
        <td><%= area.name %></td>
        <td>
          <div style="display: inline-flex;">
            <%= link_to area do %>
              <i class="material-icons left">clear_all</i>
            <% end %>
            <%= link_to edit_area_path(area) do %>
              <i class="material-icons left">edit</i>
            <% end %>
            <%= link_to area, method: :delete, data: { confirm: '¿Estás seguro de eliminar el elemento?' }  do %>
              <i class="material-icons left">delete</i>
            <% end %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/areas/new.html.erb
<h1>Nueva Área</h1>

<%= render 'form', area: @area %>

<%= link_to 'Back', areas_path %>

app/views/areas/show.html.erb
<p id="notice"><%= notice %></p>

<table class="highlight">
  <thead>
    <tr>
      <th>Servicio</th>
      <th>Área</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @area.catalog.name %></td>
        <td><%= @area.name %></td>
      </tr>
  </tbody>
</table>

<br>

<%= link_to 'Edit', edit_area_path(@area) %> |
<%= link_to 'Back', areas_path %>

app/views/catalogs/_form.html.erb
<%= form_with(model: catalog, local: true) do |form| %>
  <% if catalog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(catalog.errors.count, "error") %> prohibited this catalog from being saved:</h2>

      <ul>
      <% catalog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/catalogs/edit.html.erb
<h1>Editing Catalog</h1>

<%= render 'form', catalog: @catalog %>

<%= link_to 'Show', @catalog %> |
<%= link_to 'Back', catalogs_path %>

app/views/catalogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Servicios</h1>

<p>Para subir un servicio selecciona un archivo .csv </p>
<div style="display: table-caption;">
  <%= form_tag import_catalogs_path, multipart: true do%>
    <%= file_field_tag :file%>
    <%= submit_tag "Cargar servicios"%>
  <% end %>
</div>

<table class="highlight">
  <thead>
    <tr>
      <th>Servicios <%= link_to raw("<i class='material-icons left'>add</i>"), new_catalog_path %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @catalogs.each do |catalog| %>
      <tr>
        <td><%= catalog.name %></td>
        <td>
          <div style="display: inline-flex;">
            <%= link_to catalog do %>
              <i class="material-icons left">clear_all</i>
            <% end %>
            <%= link_to edit_catalog_path(catalog) do %>
              <i class="material-icons left">edit</i>
            <% end %>
            <%= link_to catalog, method: :delete, data: { confirm: '¿Estás seguro de eliminar el elemento?' }  do %>
              <i class="material-icons left">delete</i>
            <% end %>
          </div>
        </td>
        <!-- <td><%= link_to 'Show', catalog %></td>
        <td><%= link_to 'Edit', edit_catalog_path(catalog) %></td>
        <td><%= link_to 'Destroy', catalog, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

app/views/catalogs/new.html.erb
<h1>Nuevo Servicio</h1>

<%= render 'form', catalog: @catalog %>

<%= link_to 'Back', catalogs_path %>

app/views/catalogs/show.html.erb
<p id="notice"><%= notice %></p>

<table class="highlight">
  <thead>
    <tr>
      <th>id</th>
      <th>Servicio</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @catalog.id %></td>
        <td><%= @catalog.name %></td>
      </tr>
  </tbody>
</table>

<br>

<%= link_to 'Edit', edit_catalog_path(@catalog) %> |
<%= link_to 'Back', catalogs_path %>

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <!-- <div class="field">
    <%= form.label :area_id %>
    <%= form.text_field :area_id %>
  </div> -->
  <%=select("post", "area_id", Area.all.collect {|p| [ p.name, p.id ] })%>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<!-- <a data-js-hide-link="true" href="">Hide</a> -->
<h1>Items</h1>

<p>Para subir items selecciona un archivo .csv </p>
<div style="display: table-caption;">
  <%= form_tag import_items_path, multipart: true do%>
    <%= file_field_tag :file%>
    <%= submit_tag "Cargar items"%>
  <% end %>
</div>

<table class="highlight">
  <thead>
    <tr>
      <th>Servicio <%= link_to raw("<i class='material-icons left'>add</i>"), new_catalog_path %></th>
      <th>Área <%= link_to raw("<i class='material-icons left'>add</i>"), new_area_path %></th>
      <th>Items <%= link_to raw("<i class='material-icons left'>add</i>"), new_item_path %></th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.area.catalog.name%></td>
        <td><%= item.area.name %></td>
        <td><%= item.name %></td>
        <td>
          <div style="display: inline-flex;">
            <%= link_to item do %>
              <i class="material-icons left">clear_all</i>
            <% end %>
            <%= link_to edit_item_path(item) do %>
              <i class="material-icons left">edit</i>
            <% end %>
            <%= link_to item, method: :delete, data: { confirm: '¿Estás seguro de eliminar el elemento?' }  do %>
              <i class="material-icons left">delete</i>
            <% end %>
          </div>
           
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/items/new.html.erb
<h1>Nuevo Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<table class="highlight">
  <thead>
    <tr>
      <th>Servicio</th>
      <th>Área</th>
      <th>Item</th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @item.area.catalog.name %></td>
        <td><%= @item.area.name %></td>
        <td><%= @item.name %></td>
      </tr>
  </tbody>
</table>

<br>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ServiciosApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- <nav>
      <div class="nav-wrapper">
        <div class="brand-logo">CRUD de Servicios</div>
        <a href="#!" data-target="slide-out" class="sidenav-trigger"><i class="material-icons">menu</i></a>
      </div>
    </nav> -->
    <nav>
        <div class="nav-wrapper">
          <div class="row">
            <div class="col s7" style="font-size: 2rem;"><%= link_to 'CRUD de Servicios', items_url %></div>
            <div class="col s5" style="text-align: right;">
              <%= link_to 'Servicios', catalogs_url %>
              <%= link_to 'Áreas', areas_url %>
              <%= link_to 'Items', items_url %>
            </div>
          </div>
          <%= link_to 'CRUD de Servicios', items_url %>
        </div>
      </nav>
      <div class="container">
        <%= yield %>
      </div>
  </body>
</html>